#!/bin/bash
#SBATCH --job-name=kmer_count
#SBATCH -p general
#SBATCH -n 20
#SBATCH --mem-per-cpu=5G
#SBATCH -t 03:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=zachary.lewis@yale.edu

module load Jellyfish/2.2.10-foss-2016b

jellyfish count -t 50 -C -m 17 -o physalia_17mer -s 3G --bf-size 50G illumina_reads.fasta

#-t threads
#-C both strands considered
#-m count 25mers
#-s specifies hash size, which should be equal to or less than job memory. Here set to genome size
## actually had to reduce this to 1/4 of the total job memory, probably should do 1/5 in the future
#-o output name
# using bloom filter option to reduce memory: https://github.com/gmarcais/Jellyfish/tree/master/doc#counting-high-frequency-k-mers
## set to coverage * genome size (150G)


#generate a histogram file

jellyfish histo -o physalia_25mer.histo physalia_25mer
