#!/bin/bash
#SBATCH -p general
#SBATCH --job-name=RED
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 8
#SBATCH --mem-per-cpu=5G
#SBATCH -t 0-10:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=zachary.lewis@yale.edu
#SBATCH -o RED.%j.out
#SBATCH -e RED.%j.err

module load Python/2.7.13-foss-2016b

./redmask.py -i  ../BUSCO_analysis/physalia_pilonPolished.concat.scaffolds.fa -o physalia_pilonPolished.concat.scaffolds_RED.fa
